// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnLVomY8mrYJeyIKo4Zv6hdN-fxMy6A_w',
    appId: '1:574916157829:web:867ee372bfb56a20bb64ec',
    messagingSenderId: '574916157829',
    projectId: 'bolao-359916',
    authDomain: 'bolao-359916.firebaseapp.com',
    storageBucket: 'bolao-359916.appspot.com',
    measurementId: 'G-1D3JGFTE2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ny-KuYdNBztsNFhMmlxfiRPJJnv1cq8',
    appId: '1:574916157829:android:1a5d43561980b99cbb64ec',
    messagingSenderId: '574916157829',
    projectId: 'bolao-359916',
    storageBucket: 'bolao-359916.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFrTLenyPVi7YQ-fBc-nzB1zTrXCM1zL4',
    appId: '1:574916157829:ios:1c92744b60a04970bb64ec',
    messagingSenderId: '574916157829',
    projectId: 'bolao-359916',
    storageBucket: 'bolao-359916.appspot.com',
    androidClientId: '574916157829-af3m6rgu89itu42fpgppko2rgacb9s6m.apps.googleusercontent.com',
    iosClientId: '574916157829-j1ejdekld9gkqrb5717ugsdgnc0e86vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.bolaoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFrTLenyPVi7YQ-fBc-nzB1zTrXCM1zL4',
    appId: '1:574916157829:ios:1c92744b60a04970bb64ec',
    messagingSenderId: '574916157829',
    projectId: 'bolao-359916',
    storageBucket: 'bolao-359916.appspot.com',
    androidClientId: '574916157829-af3m6rgu89itu42fpgppko2rgacb9s6m.apps.googleusercontent.com',
    iosClientId: '574916157829-j1ejdekld9gkqrb5717ugsdgnc0e86vf.apps.googleusercontent.com',
    iosBundleId: 'com.example.bolaoApp',
  );
}
